### ISSUE TITLE
emily core despawns

### ISSUE THREAD

**Issue by me3127** [SecondFaceSoftware/PortalRevolution-Issues#100] opened 2024-01-12 02:24 UTC
**bug description**
right after the very first time you meet emily, you have to plug her into a wall socket. If you put here there before the socket comes out of the wall, she will despawn entirely. Even upon ejecting, she will simply not exist. This happened to me once I did not attempt to repeat it. 

**To Reproduce**
1. obtain emily
2. place her as far into the wall with the socket plug as you can get *before* the socket emerges
3. she has despawned and progress is now impossible. 

**Expected behavior**
I expected this to not happen. 

**Screenshots**
Didnt think to do this. 

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - GPU name: Sapphire PULSE Radeon RX 5700 XT 8 GB Video Card
 - CPU name: [AMD Ryzen 5 3600X 3.8 GHz 6-Core Processor]
 - RAM (Quantity + Spec): [Corsair Vengeance LPX 16 GB (2 x 8 GB) DDR4-3000 CL15 Memory]

**Comment by Mystical-Ace** [comment] 2024-01-19 18:09
Duplicate of #2

**Closed by Mystical-Ace** 2024-01-19 18:09 UTC
Labels: bug
