### ISSUE TITLE
Personality core disappears after plugging it too fast for the first time 

### ISSUE THREAD

**Issue by FcFritz** [SecondFaceSoftware/PortalRevolution-Issues#174] opened 2024-01-23 16:50 UTC
**Describe the bug**
If you place the personality core in the "wall plug" beafore it appears on the screen, the personality core disappears and isn't retrievable any more.

**To Reproduce**
1. Look at the window to trigger the "wall plug" event. 
2. Position the personality core where the "wall plug" will appear.
3. The bug occurs and now the personality core disappears.

**Expected behavior**
It was expected for the personality core to attach itself to the "wall plug"

**Videos**
Video recreating the bug: https://youtu.be/tbDUtuXEVAM

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU name: NVIDIA GeForce GTX 1650
 - CPU name: AMD Ryzen 7 4800H with Radeon Graphics
 - RAM (Quantity + Spec): 8 GB, 2 slots, SODIMM, 3200 MHz

**Comment by CandyCornNuts** [comment] 2024-01-26 20:55
I ran in to this as well. I noticed the core spawns in the tube across the room!
![core_in_wrong_place](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/61322233/4d05bc2e-cd5c-4e6d-bb28-afd7cbf53cc9)

**Comment by Mystical-Ace** [comment] 2024-01-28 07:14
Duplicate of #2

**Closed** 2024-01-28 07:14 UTC
Labels: bug
