### ISSUE TITLE
game hardlock my pc

### ISSUE THREAD

**Issue by Foxaryse** [SecondFaceSoftware/PortalRevolution-Issues#4] opened 2024-01-06 21:10 UTC
**Describe the bug**
the game just hardlock my pc

**To Reproduce**
1. Go to (currently start chapter 3
2. Start discord Stream
3. entire PC not responding but still have discord sound (PC HARDLOCK)
4. force restart PC

**Expected behavior**
not my PC to HARDLOCK

**Screenshots**
No need because it just an frozen screen

**Desktop (please complete the following information):**
 - OS: Windows 11
 - GPU name: RTX 4070
 - CPU name: Ryzen 5950x
 - RAM (Quantity + Spec): 32Gb, 3200Mhz
 
 Contact info:
 Discord : foxaryse (currently on the discord server)
 Gmail : foxaryse@gmail.com

**Comment by Foxaryse** [comment] 2024-01-06 21:13
it did it to me an second time but wen i tried an third time while recording on my phone the problem won't redo

**Comment by Foxaryse** [comment] 2024-01-06 21:17
first time:
was start chapter 3
moved to discord an mute an stream and got back to the game quickly 
PC HARDLOCK (only holding the power button working)

Second time:
started Chap3
started screensharing on discord
PC HARDLOCK (same result)

Third time will recording on my phone:
retried step 1 and 2, not getting the same result

**Comment by Foxaryse** [comment] 2024-01-07 13:32
UPDATE it did it again but i recorded this time https://youtu.be/COkpLGgLDsk

**Comment by StefanH-AT** [comment] 2024-12-04 14:46
Considering this is caused by discord screenshare, and since nobody else has encountered this issue, I'll have to close this

**Closed by StefanH-AT** 2024-12-04 14:46 UTC
Labels: bug
