### ISSUE TITLE
Orange gel screen effect for being hit by gel has an unusual green effect on top of it

### ISSUE THREAD

**Issue by Wheattttt** [SecondFaceSoftware/PortalRevolution-Issues#31] opened 2024-01-07 10:57 UTC
**Describe the bug**
When the player is covered in orange gel, the orange screen effect is present, but so is a green one that doesn't fade out properly. It seems to persist for a while, before instantly vanishing after a little too long

**To Reproduce**
1. Go to a map with orange gel (I'm on the first one)
2. Get coated in it
3. See the green

**Expected behavior**
There should not be a constantly visible green overlay, it should just be the orange one that correctly fades.

**Screenshots**

https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/33504404/7dd7cf7f-484f-4323-b1f4-2f683a2d17b1

**Desktop:**
- OS: Microsoft Windows 11 Home
- GPU name: NVIDIA GeForce RTX 3060 Ti
- CPU name: Intel(R) Core(TM) i5-13600KF
- RAM (Quantity + Spec): 32 GB

**Comment by mirnovov** [comment] 2024-01-08 11:09
Seems to be a duplicate of #15

**Closed** 2024-01-12 20:25 UTC
Labels: bug
