### ISSUE TITLE
Soft-lock on "The Cutting Room Floor"

### ISSUE THREAD

**Issue by T-kON99** [SecondFaceSoftware/PortalRevolution-Issues#83] opened 2024-01-10 15:02 UTC
**Soft-lock on "The Cutting Room Floor"**

**To Reproduce**
1. Load a save nearing the end of "The Cutting Room Floor" just before you plug the ball into the wall.
2. Before the story / cutscene progresses, wait and stand by near the wall.
3. Let the story continues and allow player to plug in the ball to the wall
4. Ball teleports and player have no way to obtain the ball back because it is out of boundary

**Expected behavior**
Ball should not be teleported away

**Screenshots**
![image](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/37513543/583ce3d3-ab75-4418-97b8-aabc1b7234f6)
![image](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/37513543/af48e7ed-dc1c-4154-9223-325867532d12)
![8bvztr](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/37513543/8c49fbb4-4d3f-4d3c-bc00-7ae8ad886a4b)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU name: RTX 3060Ti
 - CPU name: AMD Ryzen 7 5800X
 - RAM (Quantity + Spec): 32GB ddr5 3.6MHz

I can attach save files if required.

**Comment by ArcherTheReal** [comment] 2024-01-10 22:34
You don't actually need to load a save it works by just being very close to the thing

**Comment by Mystical-Ace** [comment] 2024-01-20 10:51
Duplicate of #2

**Closed** 2024-01-20 10:52 UTC
Labels: bug
