### ISSUE TITLE
Pressing core into core insert will cause the core to teleport away

### ISSUE THREAD

**Issue by SomeAspy** [SecondFaceSoftware/PortalRevolution-Issues#49] opened 2024-01-08 01:17 UTC
**Describe the bug**
Pressing the personality core into the expected area for the port to pop out will cause the core to teleport to an inaccessible area and soft lock the game

**To Reproduce**
1. before the core connector port thing pops out, press the core against the the area of the wall where it will pop out
2. Core will teleport out of accessible area

**Expected behavior**
Core should not teleport

**Screenshots**

https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/33640860/208e2f5b-286c-4ad0-8ffd-c1c5afe2c0d3

**Desktop (please complete the following information):**
 - OS:  Arch (rolling)
 - GPU name:  AMD Radeon RX 6650 XT
 - CPU name:  AMD Ryzen 7 5800X3D (16) @ 3.40 GHz
 - RAM (Quantity + Spec): 64GB DDR4 @ 3200 MHz

**Comment by Mystical-Ace** [comment] 2024-01-19 18:04
Duplicate of #2

**Closed by Mystical-Ace** 2024-01-19 18:04 UTC
Labels: bug

**Comment by SomeAspy** [comment] 2024-01-20 04:20
I totally missed that, my bad
