### ISSUE TITLE
Conly disappears and softlocks you

### ISSUE THREAD

**Issue by tellatale1** [SecondFaceSoftware/PortalRevolution-Issues#120] opened 2024-01-13 12:53 UTC
Description:
Holding Conly on the wall plug before it appears makes Conly disappear once it is available. After she is supposed to be ejected, she doesn't appear, I tried grabbing her thinking she was just invisible but to no avail. After that, if you pick up a chair you can't let go of it, but getting it stuck and moving the camera away drops it.

1. In chapter 5, after grabbing Conly for the first time, get past the dark area.
2. Hold Conly where the wall plug will appear (the corner of the room with the yellow and black lines).
3. Hold her there until the wall plug appears.

Expected behavior:
Once the wall plug appears, Conly gets plugged, does her stuff, and then gets ejected for the player to pick up.

Desktop:
 - OS: Windows 10
 - GPU name: Gigabyte 6700XT GAMING OC
 - CPU name: Ryzen 5 5600X
 - RAM: 2x16 GB 3200MHz

**Comment by TBirdSoars** [comment] 2024-01-16 02:27
Same here, I can't get past this part. 

Also, I've tried saving in that room before looking out the window, but now reloading the save breaks the dialogue and I can't continue.

**Comment by MBReivax** [comment] 2024-01-16 11:09
I also had this issue

https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/46864432/dabca41b-3828-4db0-974f-267b5fbb24fc

**Comment by tellatale1** [comment] 2024-01-16 12:02
I guess I should've said that moving her to the wall plug after it finishes its animation works fine. 

> I also had this issue
> 
>  016-CuteBlueBallDisappear10MB.mp4

This video shows it perfectly, thanks.

**Comment by Mystical-Ace** [comment] 2024-01-19 18:10
Duplicate of #2

**Closed by Mystical-Ace** 2024-01-19 18:10 UTC
Labels: bug
