### ISSUE TITLE
Lost the Personality Core when Not Supposed to

### ISSUE THREAD

**Issue by normoe445** [SecondFaceSoftware/PortalRevolution-Issues#159] opened 2024-01-20 19:38 UTC
**Describe the bug**
During the Cutting Room Floor chapter, I got the lady inside the Personality Core, and she led me to the plug in the wall that I need to plug her into in order to progress. I put her against the wall before the animation of it opening played, and she got stuck inside, and I was not able to get her out, and was prevented from progressing.

**To Reproduce**
1. Go to the room where the Personality Core asks to look out the window shortly after you first get her.
2. after you have triggered her dialogue, go to where the plug will open from and hold her in front of it.
3. The plug box will then close, and she will be sucked inside the wall, and you will need to go to a previous save in order to undo it.

**Expected behavior**
I expected that she would not be stuck inside the wall and would be on the plug.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - GPU name: AMD Raedon RX 6800 XT
 - CPU name: 12th Gen Intel Core i7-12700K
 - RAM (Quantity + Spec): 32 GB

**Comment by Mystical-Ace** [comment] 2024-01-20 21:17
Likely a dupe of #2

**Closed by Mystical-Ace** 2024-01-20 21:17 UTC
Labels: bug
