### ISSUE TITLE
Blue sphere disappears

### ISSUE THREAD

**Issue by CrazySniper3107** [SecondFaceSoftware/PortalRevolution-Issues#162] opened 2024-01-21 04:31 UTC
**Describe the bug**
In chapter 5 when attempting to place the sphere into the hub/wall port, it will disappear. I have reproduced the bug more than once; it should happen so long as the sphere is held directly against the hub when it goes to connect. After turning invisible, it can't be picked up, but you can still hear voice lines so...

**To Reproduce**
1. Take sphere to the hub
2. Walk forwards, holding the sphere against the hub
3. Keep walking forwards against the wall until it takes the sphere.

**Expected behavior**
Hub takes sphere, shortly after, drops it so player can pick it up.

**Screenshots**
Sphere turns invisible so no screenshots.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - GPU name: Intel(R) UHD Graphics 620
 - CPU name: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz 
 - RAM (Quantity + Spec): 8.00

**Comment by Mystical-Ace** [comment] 2024-01-21 11:06
Duplicate of #2

**Closed by Mystical-Ace** 2024-01-21 11:06 UTC
Labels: bug
