### ISSUE TITLE
Brightness settings are able to go way beyond intended levels. 

### ISSUE THREAD

**Issue by iidxgold** [SecondFaceSoftware/PortalRevolution-Issues#18] opened 2024-01-07 00:16 UTC
Simple as title states. You can input any number up to 1000% in the brightness settings, which is very ludicrous and feels unintended. 

To Reproduce:

Go to Settings
Go to Video
Click on "Brightness"
Type in any number up to 1000.

I expected this to cap out at a reasonable amount, maybe 250%? 

 - OS: Windows 10
 - GPU name: NVIDIA GeForce GPU
 - CPU name: Intel(R) Core(TM) i7-4765T CPU @ 2.00GHz   2.00 GHz
 - RAM (Quantity + Spec): 16GB

![Screenshot (44)](https://github.com/SecondFaceSoftware/PortalRevolution-Issues/assets/136996781/b60aa362-c394-4afe-aed0-145c6e295f0b)

**Comment by Mystical-Ace** [comment] 2024-01-19 18:03
Closing this as not a bug since it can be potentially useful for those where the max slider is not bright (or dim) enough for them

**Closed** 2024-01-19 18:04 UTC
Labels: bug
